### ISSUE TITLE
Mypy fails when exception handler is turned on

### ISSUE THREAD

**Issue by gcarvellas** [castlepointanime/backend#36]
**Describe the bug**
mypy fails because of the exception handler in `app.py`. It's commented out right now but it shouldn't be.

**Comment by Yun-L** [comment]
the error handler decorator expects a function that returns a `ResponseReturnValue`, defined in https://github.com/pallets/flask/blob/ed5b240417414cbd0322efa95c91f759928ba154/src/flask/typing.py#L32

our `FlaskResponseType` gives us a type error, but looks like it's almost the same as  `ResponseValue` (a subtype of `ResponseReturnValue`. Is there a reason why we are using our own return type for route functions instead of the flask defined one?

**Comment by gcarvellas** [comment]
> the error handler decorator expects a function that returns a `ResponseReturnValue`, defined in https://github.com/pallets/flask/blob/ed5b240417414cbd0322efa95c91f759928ba154/src/flask/typing.py#L32
> 
> 
> 
> our `FlaskResponseType` gives us a type error, but looks like it's almost the same as  `ResponseValue` (a subtype of `ResponseReturnValue`. Is there a reason why we are using our own return type for route functions instead of the flask defined one?

Let's use the flask defined return types instead
